### ISSUE TITLE
Getting patches upstream

### ISSUE THREAD

**Issue by kallisti5** [X547/Haiku-riscv#1]
Good morning!

I was able to get your test image booted on my SiFive unmatched. Nice work!!!

Should we be throwing away the riscv64 patches in Gerrit and replacing them with the patches in this git repository?

**Comment by X547** [comment]
> Should we be throwing away the riscv64 patches in Gerrit and replacing them with the patches in this git repository?

No, it should be just updated. Many patches already have Gerrit ID.

**Comment by X547** [comment]
I hope will update Gerrit patches this week. I already rebased them for latest Haiku revision.

**Comment by kallisti5** [comment]
Cool.  Let me know if you need help in any way.  Thanks!

**Comment by X547** [comment]
Done.
